"""
Django settings for capstone_site project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.core.management.utils import get_random_secret_key
from dotenv import load_dotenv

import sys
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
load_dotenv()
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production
DEBUG = os.getenv("DEBUG", "False") == "True"

DEVELOPMENT_MODE = os.getenv("DEVELOPMENT_MODE", "False") == "True"

USE_SPACES = os.getenv("USE_SPACES", "False") == "True"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS]

MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'

LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # 3rd party
    'crispy_forms',
    'crispy_bootstrap5',
    'bootstrap_datepicker_plus',
    'rest_framework',
    'rest_framework.authtoken',
    'storages',
    'anymail',
    'django_cleanup', # for testing
    # SERVICE APPS
    'api',
    'home',
    'django_login',
    'events',
    'management.apps.ManagementConfig',
    'files',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = 'bootstrap5'

BOOTSTRAP_DATEPICKER_PLUS = {
    'options': {
        'locale': 'es',
        'showClose': True,
        'showClear': True,
        'showTodayButton': True,
    },
    'variant_options': {
        'date': {
            'format': 'DD-MM-YYYY',
        },
    },
    'attrs': {
        'class': 'datepicker'
    }
}

# Anymail settings
ANYMAIL = {
    'MAILGUN_API_KEY': os.getenv('MAILGUN_API_KEY'),
    'MAILGUN_SENDER_DOMAIN': 'mg.acreditacionesqr.online'
}
EMAIL_BACKEND = 'anymail.backends.mailgun.EmailBackend'
DEFAULT_FROM_EMAIL = 'postmaster@mg.acreditacionesqr.online'
SERVER_EMAIL = 'postmaster@mg.acreditacionesqr.online'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ] 
}

AUTH_USER_MODEL = 'management.Acreditador'

# SSL settings, enable them if you're hosting the site, don't if you're not
CSRF_COOKIE_SECURE = True

SESSION_COOKIE_SECURE = True

# Don't enable this one if you're hosting it on App Plat / have Apache or Nginx do it for u
# SECURE_SSL_REDIRECT = True

SECURE_BROWSER_XSS_FILTER = True

ROOT_URLCONF = 'capstone_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'management.context_processors.eventos_recientes',
            ],
        },
    },
]

WSGI_APPLICATION = 'capstone_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if DEVELOPMENT_MODE is True:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }
elif len(sys.argv) > 0 and sys.argv[1] != 'collectstatic':
    if os.getenv("DATABASE_URL", None) is None:
        raise Exception("DATABASE_URL environment variable is not defined")
    DATABASES = {
        "default": dj_database_url.parse(os.environ.get("DATABASE_URL"))
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Digital Ocean space settings
USE_SPACES = os.getenv("USE_SPACES", "False") == "True"

if USE_SPACES is True: 
    DO_ACCESS_KEY = os.getenv('BUCKET_ACCESS_KEY')
    DO_SECRET_KEY = os.getenv('BUCKET_SECRET_KEY')
    BUCKET_NAME = os.getenv('BUCKET_NAME')
    ENDPOINT_URL = 'https://nyc3.digitaloceanspaces.com'

    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3StaticStorage',
            'OPTIONS': {
                'access_key': DO_ACCESS_KEY,
                'secret_key': DO_SECRET_KEY,
                'region_name': 'nyc3',
                'bucket_name': BUCKET_NAME,
                'endpoint_url': ENDPOINT_URL,
                'location': 'media',
                'default_acl': 'private',
                'custom_domain': f'{BUCKET_NAME}.nyc3.cdn.digitaloceanspaces.com',
                'file_overwrite': False,
                'querystring_auth': True,
            },
        },
        'staticfiles': {
            'BACKEND': 'storages.backends.s3.S3StaticStorage',
            'OPTIONS': {
                'access_key': DO_ACCESS_KEY,
                'secret_key': DO_SECRET_KEY,
                'region_name': 'nyc3',
                'bucket_name': BUCKET_NAME,
                'endpoint_url': ENDPOINT_URL,
                'location': 'staticfiles',
                'default_acl': 'public-read',
                'custom_domain': '%s.nyc3.cdn.digitaloceanspaces.com' % (BUCKET_NAME)
            },
        },
    }

    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

    STATIC_URL = f'https://{BUCKET_NAME}.nyc3.cdn.digitaloceanspaces.com/staticfiles/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')

    #Media files settings
    MEDIA_URL = f'https://{BUCKET_NAME}.nyc3.cdn.digitaloceanspaces.com/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
    STATIC_URL = '/static/'
    STATIC_ROOT = BASE_DIR / 'static/'

    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
