# Generated by Django 5.1 on 2024-11-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[(0, 'Consulta'), (1, 'Envío de nómina')])),
                ('mensaje', models.TextField(max_length=300)),
                ('archivo', models.FileField(null=True, upload_to='uploads/tmp')),
                ('hora_subido', models.DateTimeField(auto_now_add=True)),
                ('aceptado', models.BooleanField(default=False)),
            ],
        ),
    ]
