# Generated by Django 5.1 on 2024-09-04 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acceso', models.CharField(choices=[('NA', 'Sin Acceso'), ('WP', 'Working Pass'), ('AA', 'All Access'), ('AAA', 'All Areas Access'), ('S', 'Seguridad'), ('T', 'Ticketmaster')], default='NA', max_length=3)),
                ('desc_acceso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_evento', models.CharField(max_length=50)),
                ('fec_inicio', models.DateField()),
                ('fec_termino', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='event_images')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rol', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Acreditador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_acreditador', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('app_paterno', models.CharField(max_length=40)),
                ('app_materno', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=40, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=40, unique=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Acreditado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('id_pulsera', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('app_paterno', models.CharField(max_length=40)),
                ('app_materno', models.CharField(max_length=40)),
                ('fec_inicio', models.DateTimeField()),
                ('fec_termino', models.DateTimeField()),
                ('acceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.acceso')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.empresa')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.rol')),
            ],
        ),
    ]
