# Generated by Django 5.1 on 2024-11-16 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acreditacion',
            name='acreditado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.acreditado'),
        ),
        migrations.AlterField(
            model_name='acreditacion',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.evento'),
        ),
    ]
