# Generated by Django 5.1 on 2024-09-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceso',
            name='tipo_acceso',
            field=models.CharField(choices=[('SA', 'Seleccionar acceso'), ('WP', 'Working Pass'), ('AA', 'All Access'), ('AAA', 'All Areas Access'), ('S', 'Seguridad'), ('T', 'Ticketmaster')], default='SA', max_length=3),
        ),
    ]
