# Generated by Django 5.1 on 2024-09-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_acceso_tipo_acceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acreditado',
            name='fec_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='acreditado',
            name='fec_termino',
            field=models.DateField(),
        ),
    ]
