# Generated by Django 5.1 on 2024-10-01 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_acreditado_fec_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceso',
            name='tipo_acceso',
            field=models.CharField(choices=[('SA', 'Seleccionar acceso'), ('WP', 'Working Pass'), ('AA', 'All Access'), ('AAA', 'All Areas Access'), ('S', 'Seguridad')], default='SA', max_length=3),
        ),
        migrations.CreateModel(
            name='Acreditacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acreditacion', models.DateField()),
                ('acreditado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.acreditado')),
                ('acreditador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.acreditador')),
            ],
        ),
    ]
